### ISSUE TITLE
Automated Greetings 

### ISSUE THREAD

**Issue by sanmarg** [Chit-Chat-Org/Chit-Chat#7]
I propose to create a GitHub workflow named "Greetings". This workflow will automatically greet(Using Github bots) users who create new issues or pull requests in this repository.  The Greeting will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible."

Please assign this issue to me

![image](https://github.com/Chit-Chat-Org/Chit-Chat/assets/50082154/8b553b8f-302e-4c3c-8189-7fd1768b7fde)

**Comment by apurvjha123** [comment]
Hey sanmarg,
make sure you do it within 2 days
also if you want, you can put a pr this in all of the three out there.

**Comment by sanmarg** [comment]
Could you please assign the level to this task? Also, I wish to inform you that I have completed the task before the deadline.
