### ISSUE TITLE
[DOC] : update CODE OF CONDUCT file.

### ISSUE THREAD

**Issue by anglerfishlyy** [Chit-Chat-Org/Chit-Chat#8]
The code of conduct file doesn't have good styling , proper arrangement of text and has errors.(grammatical errors) .

* It would be awesome to update code of conduct file as it is read by the contributors in the first place to understand how to be in an open source contributing environment.

* Guiding Behavior: The code of conduct sets guidelines for expected behavior within repositories.

* Ensuring Respect: It fosters an environment of respect, inclusivity, and professionalism among contributors.

* Handling Conflict: The code provides a framework for addressing conflicts or unacceptable behavior.

* Maintaining Standards: It helps maintain high standards of interaction and collaboration within the community.

* Setting Expectations: Contributors understand the conduct expected of them when participating in the project.

therefore , having proper _code of conduct_ file is more than important.

**Comment by anglerfishlyy** [comment]
can you assign and label this to me?

**Comment by apurvjha123** [comment]
go ahead.
