### ISSUE TITLE
FEATURE: MAKE FIELDS REQUIRED

### ISSUE THREAD

**Issue by Manishak798** [Chit-Chat-Org/Chit-Chat#9]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/Chit-Chat-Org/Chit-Chat/assets/90680330/17bffc04-0b56-45e1-bf1c-8bc28dfdf4b5)
 
As a user when i look up to the sign in sign up form I can not tell which field is mandatory to fill as from the frontend side no field is marked as required like we normally do with the ( * ) sign.

**Describe the solution you'd like**
Make all necessary fields marks as required from the frontend side, it is a beginner friendly issue for contributors to kickstart there contribution journey.

**Additional context**
I am a **MENTOR** in **GSSoC'24** raising this issue for contributors to contribute.

**Comment by 2004Abhi** [comment]
Hey ! I am excited to contribute to this issue can you assign it to me?

**Comment by ApurvaBasule** [comment]
hey @2004Abhi you still working on it? if not @apurvjha123 please assign it to me.

**Comment by 2004Abhi** [comment]
@ApurvaBasule I have created a pull request which is not merged yet.
